import type { NextApiRequest, NextApiResponse } from 'next';
import nodemailer from 'nodemailer';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { audience, topic, goal, tone, email } = req.body;

  if (!audience || !topic || !goal || !tone || !email) {
    return res.status(400).json({ error: 'Missing fields' });
  }

  const prompt = `
Create a 5-page lead magnet based on the following:

Audience: ${audience}
Topic: ${topic}
Goal: ${goal}
Tone: ${tone}

Include:
1. A catchy title
2. An engaging introduction
3. 3–5 helpful sections
4. A strong conclusion with a call to action

Use clear formatting, short paragraphs, and bullet points where appropriate.
`;

  try {
    // 🔹 Call OpenAI
    const aiResponse = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model: 'gpt-4o',
        messages: [
          { role: 'system', content: 'You are a professional marketing assistant.' },
          { role: 'user', content: prompt },
        ],
        temperature: 0.7,
      }),
    });

    const json = await aiResponse.json();

    if (!json.choices || !json.choices[0]?.message?.content) {
      const errorMsg = json?.error?.message || 'No content returned';
      throw new Error(`OpenAI Error: ${errorMsg}`);
    }

    const content = json.choices[0].message.content;

    // 🔹 Create styled HTML
    const html = `
      <html>
        <head>
          <style>
            body {
              font-family: Arial, sans-serif;
              padding: 40px;
              line-height: 1.6;
              color: #333;
            }
            h1 {
              color: #2C3E50;
              font-size: 26px;
              margin-bottom: 20px;
            }
            p {
              margin-bottom: 10px;
            }
            .footer {
              margin-top: 40px;
              font-size: 12px;
              color: #aaa;
            }
          </style>
        </head>
        <body>
          <h1>Lead Magnet: ${topic}</h1>
          ${content.split('\n').map((line: string) => `<p>${line.trim()}</p>`).join('')}
          <div class="footer">Generated by Lead Magnet App</div>
        </body>
      </html>
    `;

    // 🔹 Call PDFShift to convert HTML to PDF
    const pdfResponse = await fetch('https://api.pdfshift.io/v3/convert', {
      method: 'POST',
      headers: {
        'Authorization': 'Basic ' + Buffer.from(`${process.env.PDFSHIFT_API_KEY}:`).toString('base64'),
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ source: html, sandbox: true }),
    });

    if (!pdfResponse.ok) {
      throw new Error(`PDFShift error: ${pdfResponse.statusText}`);
    }

    const pdfBytes = await pdfResponse.arrayBuffer();

    // 🔹 Send email with Nodemailer
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: Number(process.env.SMTP_PORT),
      secure: false,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    await transporter.sendMail({
      from: 'test@leadmagnet.dev',
      to: email,
      subject: 'Your Lead Magnet PDF',
      text: 'Here is your custom lead magnet!',
      attachments: [
        {
          filename: 'lead-magnet.pdf',
          content: Buffer.from(pdfBytes),
        },
      ],
    });

    res.status(200).json({ message: 'PDF sent successfully', content });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to generate or send content' });
  }
}
